config/routes.rb
RailsFortune::Application.routes.draw do

  match 'auth/failure' => 'session#failure'
  match 'auth/:provider/callback' => 'session#create'
  match 'signout' => 'session#destroy'

  resources :comments do
    collection do
      get :vote
    end
  end

  resources :fortunes do
    collection do
      get :falling
      get :random
      get :random_fortunes
      get :nofortunes
    end
  end

  root :to => 'fortunes#index'  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :fortune
  belongs_to :user

  validates :content, :presence => true, :length => 3...250
  validates :author, :length => 3...50, :unless => :user_id?
  acts_as_voteable
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  validates :content, :presence => true, :length => { :minimum => 3 }
  validates :author, :presence => true, :length => { :minimum => 3 }
  paginates_per 4

  SummaryLength = 75

  def content_short
    if content.length > SummaryLength
      content.slice(0 ... SummaryLength) + "..."
    else
      content
    end
  end
  
  def latest_comments
    comments.order "created_at DESC"
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter

  def self.create_with_omniauth auth
    create! do |user|
      user.uid = auth[:uid]
      if(!auth[:info].nil?)
        user.name = auth[:info][:name] #auth[:user_info][:name] 
      end
      user.provider = auth[:provider]
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private

  def authenticate 
    if current_user.nil?
      session[:return_to] = request.url
      redirect_to '/auth/github'
    end
  end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def vote
    @comment = Comment.find_by_id params[:id]
    @user = current_user
    @already_voted = !@user.nil? ? @user.voted_on?(@comment) : false

    if(!@user.nil? && !@already_voted) 
      if params[:plus].to_i == 1
        @user.vote_for @comment
      else
        @user.vote_against @comment
      end
      respond_to do |format|
        format.js
      end
    end
  end

  # GET /comments
  # GET /comments.json
  def index
    @fortune_id = params[:fortune_id]
    @comments = Comment.where(:fortune_id => @fortune_id)
    
    respond_to do |format|
      format.js
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])
    if !current_user.nil?
      @comment.user_id = current_user.id
      @comment.author = nil
    end
    @comment.save

    respond_to do |format|
      format.js
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :ok }
    end
  end
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  before_filter :authenticate, :except => [ :random, :index, :nofortunes, :show, :random_fortunes, :falling ]

  # GET /fortunes
  # GET /fortunes.json
  def index
    if Fortune.count == 0
      render :action => 'nofortunes'
      return
    end
    @fortunes = Fortune.page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @fortunes }
    end
  end

  def nofortunes
    respond_to do |format|
      format.html
    end
  end

  def random_fortunes
    random_idx = rand(Fortune.count)
    @fortunes = Fortune.offset(random_idx).limit(4)
    respond_to do |format|
      format.json { render json: @fortunes }
    end
  end

  def random
    if(Fortune.count == 0)
      render :action => 'nofortunes'
    else
      random_idx = rand(Fortune.count)

      @fortune = Fortune.first(:offset => random_idx);
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def falling

    respond_to do |format|
      format.html
    end
  end


  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(params[:fortune])

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortune was successfully created.' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Fortune was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_uid_and_provider(auth[:uid],auth[:provider]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id

    unless session[:return_to].nil?
      redirect_to session[:return_to]
      session[:return_to] = nil
    else
      redirect_to root_url
    end
  end

  def destroy 
    session[:user_id] = nil;
    redirect_to root_url
  end

  def failure
    session[:user_id] = nil;
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def unique_field_id comment, field_name
    "comment_#{h field_name}_#{comment.fortune_id}"
  end
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<div class="comment_vote" id="comment_vote_<%= comment.id %>">
		<%= render :partial => 'comments/comment_vote', :locals => { :comment => comment } %>
	</div>
	<p>
		<%= comment.content %>
	</p>

	<p class="author">
	  <% if comment.user %>
	    <%= comment.user.name %>
	  <% else %>
            <%= comment.author %>
          <% end %>
	</p>
</div>

app/views/comments/_comment_vote.html.erb
[ <%= comment.plusminus %> ] <%= link_to '+', vote_comments_path(:id => comment.id, :plus => 1), :remote => true %> <%= link_to '-', vote_comments_path(:id => comment.id, :plus => 0), :remote => true %>

app/views/comments/_form.html.erb
<%= form_for(comment, :remote => true, :html => { :id => unique_field_id(comment, :new_comment) }) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content,{ :id => unique_field_id(comment, :content) } %>
  </div>
  <% if current_user.nil? %>
    <div class="field">
      <%= f.label :author, { :for => unique_field_id(comment, :author) } %><br />
      <%= f.text_field :author, { :id => unique_field_id(comment, :author) } %>
    </div>
  <% end %>
  <%= f.hidden_field :fortune_id, { :id => unique_field_id(comment, :fortune_id) } %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var partial = "<%= escape_javascript render :partial => "comment", :locals => { :comment => @comment } %>";
var commentsDiv = $("#comments_<%= @comment.fortune_id %>");
var commentsListDiv = $("div.commentsList", commentsDiv);
var newCommentForm = $("div.newComment > form", commentsDiv);
var newCommentDiv = $("div.newComment", commentsDiv);


<% if @comment.valid?  %>
	 commentsListDiv.prepend(partial);
	 var commentDiv = $("div.comment:first", commentsListDiv);
	 commentDiv.hide();
	 commentDiv.show("bounce", {}, 300);
	 newCommentForm[0].reset();

	 var newCommentPartial = "<%= escape_javascript render :partial => "form", :locals => { :comment => @comment.fortune.comments.new  } %>";	

<% else %>

	 var newCommentPartial = "<%= escape_javascript render :partial => "form", :locals => { :comment => @comment } %>";	
<% end %>
newCommentDiv.html(newCommentPartial);

<% if !@comment.valid? %>
	 newCommentDiv.hide();
	 newCommentDiv.show("bounce", {}, 300);
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.js.erb
<% comments.each do |comment| %>
		$("comments_<%= @fortune_id %>").html("<%=
render :partial => comment, :locals => {:comment => comment }
%>");
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>Author:</b>
  <%= @comment.author %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/vote.js.erb
<% if @user.nil? %>
	 alert("You need to be logged in");
<% elsif @already_voted %>
	 alert("You have already voted for this comment");
<% else %>

var voteMenu = $("div#comment_vote_<%= @comment.id %>");
var voteMenuHtml = "<%= escape_javascript render :partial => 'comments/comment_vote', :locals => { :comment => @comment } %>";

voteMenu.html(voteMenuHtml);
voteMenu.show('pulsate', {}, 300);

<% end %>

app/views/fortunes/_falling_fortune.html.erb
<div class="fallingFortune" id="fallingFortuneTemplate">
	<div class="fortuneId">${id}</div>
	${author}
	<div class="comicBalloon">
		<p class="text">
			${content}
		</p>
	</div>
</div>

app/views/fortunes/_form.html.erb
<%= form_for(@fortune) do |f| %>
  <% if @fortune.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fortune.errors.count, "error") %> prohibited this fortune from being saved:</h2>

      <ul>
      <% @fortune.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fortunes/_fortune_big.html.erb
<div class="fortuneBig">
	<div class="fortuneMenu">
	  <%= link_to 'Edit', edit_fortune_path(fortune) %>
	  <%= link_to 'Delete', fortune, :confirm => 'Are you sure?', method: :delete %>
	</div>
	<%= simple_format fortune.content %>		

	<p class="author">
		<%= fortune.author %>
	</p>
	<div class="fullContent">
		<div id="comments_<%= fortune.id %>">
			<h2>Add new comment</h2>
			<div class="newComment">
				<%= render :partial => "comments/form", :locals => { :comment => fortune.comments.new } %>
			</div>
			
			<h2>Comments</h2>
			<div class="commentsList">
				<%= render :partial => "comments/comment", :collection => fortune.latest_comments %>
			</div>
		</div>
	</div>
</div>

app/views/fortunes/_fortune_list.html.erb
<% fortunes.each do |fortune| %>
<div class="gridElement">
	<%= render :partial => "fortune_big", :locals  => { :fortune => fortune }  %>
</div>
<% end %>

app/views/fortunes/edit.html.erb
<h1>Editing fortune</h1>

<%= render 'form' %>

<%= link_to 'Show', @fortune %> |
<%= link_to 'Back', fortunes_path %>

app/views/fortunes/falling.html.erb
<%= render :partial => 'falling_fortune' %>
<div id="fallingArea">

</div>

app/views/fortunes/index.html.erb
<h1>Listing fortunes</h1>
<div id="listMenu">
	<div id="pagination">
		<%= paginate @fortunes, :remote => true %>
	</div>
</div>
<div class="grid" id="fortuneList">
	<%= render :partial => "fortune_list", :locals => { :fortunes => @fortunes } %>
</div>

app/views/fortunes/index.js.erb
var paginationDiv = $("div#pagination");
var listDiv = $("div#fortuneList");
var fortunesHtml = "<%= escape_javascript render :partial => "fortune_list", :locals => { :fortunes => @fortunes } %>";
var paginationHtml = "<%= escape_javascript paginate @fortunes, :remote => true %>";

listDiv.hide("drop", {}, 400);
listDiv.html(fortunesHtml);
listDiv.show("drop", {}, 400);

paginationDiv.html(paginationHtml);

registerEventHandlers();
window.randomColors();

app/views/fortunes/new.html.erb
<h1>Add new fortune</h1>

<%= render 'form' %>

<%= link_to 'Back', fortunes_path %>

app/views/fortunes/nofortunes.html.erb
We are sorry but there are no fortunes in database. Would you like to <%=link_to 'create one', { :action => :new }%>?

app/views/fortunes/random.html.erb
<h1 class="fortuneHeader">
<%= link_to 'Get another one', { :action => :random }, :remote => true %>
</h1>
<div class="centralFortune" id="randomFortune">
	<%= render :partial => "fortune_big", :locals => { :fortune => @fortune } %>
</div>

app/views/fortunes/random.js.erb
var partial = "<%= escape_javascript render :partial => 'fortune_big', :locals => { :fortune => @fortune } %>";
var randomFortuneDiv = $('#randomFortune');
randomFortuneDiv.html(partial);
randomFortuneDiv.hide('slide', {}, 500);
randomFortuneDiv.show('slide', {}, 500);
registerEventHandlers();
window.randomColors();

app/views/fortunes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="centralFortune">
	<%= render :partial => "fortunes/fortune_big", :locals => { :fortune => @fortune } %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>railsFortune App</title>
  <meta name="description" content="Sample rails app">
  <meta name="author" content="Mateusz Szygenda">

  <!-- Mobile viewport optimized: j.mp/bplateviewport -->
  <meta name="viewport" content="width=device-width,initial-scale=1">

  
  <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

  <!-- All JavaScript at the bottom, except this Modernizr build incl. Respond.js
       Respond is a polyfill for min/max-width media queries. Modernizr enables HTML5 elements & feature detects; 
       for optimal performance, create your own custom Modernizr build: www.modernizr.com/download/ -->
  <%= javascript_include_tag "libs/modernizr-2.0.6.min.js" %>
	<%= stylesheet_link_tag    "style" %>
	<%= stylesheet_link_tag    "application" %>
	<%= stylesheet_link_tag    "fortunes" %>
	<%= stylesheet_link_tag    "comments" %>
  <%= javascript_include_tag "application" %>
	<%= javascript_include_tag "jquery-ui" %>
	<%= javascript_include_tag "libs/jquery.aautoscroll.js" %>
  <%= csrf_meta_tags %>

</head>

<body>
  <header>
    <div class="appTitle">
      railsFortune app
      <div id="mainMenu">
	<%= link_to "List", { :controller => 'fortunes' } %>
        <%= link_to "Random fortune", { :controller => 'fortunes', :action => 'random' } %>
	<%= link_to "New fortune", { :controller => 'fortunes', :action => 'new' } %>
	<%= link_to "Falling fortunes", falling_fortunes_url %>
      </div>

    <p class="auth">
    <% if current_user %>
		You are logged in as <%= current_user.name %>. 
                <%= link_to 'Sign out', '/signout' %>
		<% else %>
		You are not signed in. Do you want to <%= link_to 'sign in', '/auth/github' %> using github?
		<% end %>
		</p>
    </div>
  </header>
  <div role="main">
    <div id="content">
      <div id="infoBar">
	<div id="ajaxLoading">Loading, please wait...</div>
      </div>
      <%= yield %>
    </div>
  </div>
  <footer>
    railsFortune 2011
  </footer>
  <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
       chromium.org/developers/how-tos/chrome-frame-getting-started -->
  <!--[if lt IE 7 ]>
    <script defer src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
    <script defer>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <![endif]-->
</body>
</html>